// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tahxsobdcnbbqqonkhup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhaHhzb2JkY25iYnFxb25raHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTg4MzMsImV4cCI6MjA2NTQ3NDgzM30.v5u_b9AsF1OZZ8L-usg2D9J5esnobJAdsWFXAH_V0FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);